version: "3.8"
services:
  chat-app:
    image: helmasw/chat-app:latest
    build: . 
    container_name: chat-app
    ports:
      - "80:3000"
    environment:
    - PORT=3000
    volumes:
      - ./:/app
    command: [ "node", "app.js" ]
