version: "3.8"
services:
  chat-app:
    image: helmasw/chat-app:latest
    build: . 
    container_name: chat-app-01
    ports:
      - "80:3700"
    environment:
    - PORT=3700
    volumes:
      - ./:/app
    command: [ "node", "index.js" ]
